# Generated by Django 5.2.3 on 2025-06-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlasseRequirementItem',
            fields=[
                ('glasse_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('width', models.DecimalField(decimal_places=2, help_text='Required width in millimeters', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Required height in millimeters', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glass_requirements', to='api.material')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glass_items', to='api.subtypeglasserequirement')),
            ],
            options={
                'verbose_name': 'Glass Requirement Item',
                'verbose_name_plural': 'Glass Requirement Items',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('requirement', 'material', 'width', 'height'), name='unique_glass_dimension_per_requirement')],
            },
        ),
    ]
