# Generated by Django 5.2.3 on 2025-06-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_glasserequirementitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='glasserequirementitem',
            name='unique_glass_dimension_per_requirement',
        ),
        migrations.AlterField(
            model_name='glasserequirementitem',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='glasserequirementitem',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='glasserequirementitem',
            constraint=models.UniqueConstraint(fields=('requirement', 'width', 'height'), name='unique_glass_dimension_per_requirement'),
        ),
    ]
