# Generated by Django 5.2.3 on 2025-06-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email_alter_user_user_id_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='supply_types',
            field=models.ManyToManyField(help_text='Types of supplies this company provides', related_name='companies', to='api.supplytype'),
        ),
        migrations.AddField(
            model_name='material',
            name='supply_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='api.supplytype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_company'),
        ),
    ]
