# Generated by Django 5.2.3 on 2025-06-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_glasserequirementitem_unique_glass_dimension_per_requirement_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='glasserequirementitem',
            name='unique_glass_dimension_per_requirement',
        ),
    ]
