# Generated by Django 5.2.3 on 2025-06-24 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_glasserequirementitem_unique_glass_dimension_per_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesRequirementItem',
            fields=[
                ('req_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_requirements', to='api.material')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_items', to='api.subtypeaccessoriesrequirement')),
            ],
            options={
                'verbose_name': 'Accessories Requirement Item',
                'verbose_name_plural': 'Accessories Requirement Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MaterialRequirement',
        ),
        migrations.AddConstraint(
            model_name='accessoriesrequirementitem',
            constraint=models.UniqueConstraint(fields=('requirement', 'material'), name='unique_accessories_per_requirement'),
        ),
    ]
