# Generated by Django 5.2.3 on 2025-06-24 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accessoriesrequirementitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sketch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Sketches'},
        ),
        migrations.AddField(
            model_name='sketch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to=settings.AUTH_USER_MODEL),
        ),
    ]
