# Generated by Django 5.2.3 on 2025-06-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilealuminum',
            name='reference',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
