# Generated by Django 5.2.3 on 2025-06-20 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profilealuminum_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuresubtype',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AddField(
            model_name='structuresubtype',
            name='typeimage',
            field=models.ImageField(blank=True, null=True, upload_to='structuresubType/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
