# Generated by Django 5.2.3 on 2025-06-20 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_structuresubtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtyperequirement',
            options={'ordering': ['subtype', 'profile']},
        ),
        migrations.AddField(
            model_name='subtyperequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtyperequirement',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtype_requirements', to='api.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtyperequirement',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.structuresubtype'),
        ),
        migrations.AddConstraint(
            model_name='subtyperequirement',
            constraint=models.UniqueConstraint(fields=('subtype', 'profile'), name='unique_requirement_per_subtype_profile'),
        ),
    ]
