# Generated by Django 5.2.3 on 2025-06-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_subtyperequirement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtypeGlasseRequirement',
            fields=[
                ('glassrequirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companysupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassesupplier', to='api.company')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glassrequirements', to='api.structuresubtype')),
            ],
            options={
                'ordering': ['subtype', 'companysupplier'],
                'constraints': [models.UniqueConstraint(fields=('subtype', 'companysupplier'), name='unique_glass_requirement_per_subtype_supplier')],
            },
        ),
    ]
