# Generated by Django 5.2.3 on 2025-06-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subtypeglasserequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtypeAccessoriesRequirement',
            fields=[
                ('accessoriesrequirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companysupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoriessupplier', to='api.company')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoriesrequirements', to='api.structuresubtype')),
            ],
            options={
                'verbose_name': 'Subtype Accessories Requirement',
                'verbose_name_plural': 'Subtype Accessories Requirements',
                'ordering': ['subtype', 'companysupplier'],
                'constraints': [models.UniqueConstraint(fields=('subtype', 'companysupplier'), name='unique_accessories_requirement')],
            },
        ),
    ]
